version: "3.9"
services:
  spend-sentinel-bank-scraper:
    build: .
    container_name: spend-sentinel-bank-scraper
    environment:
      - serverUrl=http://transaction-api:8080
    env_file:
      - ./secrets/loginInformation.txt
    networks:
      - app-network

networks:
  app-network:
    external:
      name: full-spend-sentinel_app-network