version: "3.9"
services:
  spend-sentinel-bank-scraper:
    build: .
    container_name: spend-sentinel-bank-scraper
    environment:
      - serverUrl="http://localhost:8080"
    env_file:
      - ./secrets/loginInformation.txt
